services: 

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - web:/var/www/html
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - web:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  web:
    driver_opts:
      o: bind 
      type : none
      device: /home/elpira/data/web
  database:
    driver_opts:
      o: bind 
      type : none
      device: /home/elpira/data/database
